/** @file
 * Copyright (c) 2020-2023, Arm Limited or its affiliates. All rights reserved.
 * SPDX-License-Identifier : Apache-2.0

 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
**/

#include <stdio.h>
#include <stdint.h>

/** Begin config **/

extern uint32_t g_skip_array[];
extern uint32_t g_num_skip;
extern uint32_t g_test_array[];
extern uint32_t g_num_tests;
extern uint32_t g_module_array[];
extern uint32_t g_num_modules;

/* Settings */
#define PLATFORM_OVERRIDE_SBSA_LEVEL   0x7     //The permissible levels are 3,4,5,6 and 7
#define PLATFORM_OVERRIDE_PRINT_LEVEL  0x3     //The permissible levels are 1,2,3,4 and 5

/* PCIe BAR config parameters*/
#define PLATFORM_OVERRIDE_PCIE_BAR64_VAL   0x500000000
#define PLATFORM_OVERRIDE_PCIE_BAR32NP_VAL 0x60700000
#define PLATFORM_OVERRIDE_PCIE_BAR32P_VAL  0x60000000

/* PE platform config paramaters */
#define PLATFORM_OVERRIDE_PE_CNT           16
#define PLATFORM_OVERRIDE_PE0_INDEX        0x0
#define PLATFORM_OVERRIDE_PE0_MPIDR        0x0
#define PLATFORM_OVERRIDE_PE0_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE0_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE1_INDEX        0x1
#define PLATFORM_OVERRIDE_PE1_MPIDR        0x10000
#define PLATFORM_OVERRIDE_PE1_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE1_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE2_INDEX        0x2
#define PLATFORM_OVERRIDE_PE2_MPIDR        0x20000
#define PLATFORM_OVERRIDE_PE2_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE2_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE3_INDEX        0x3
#define PLATFORM_OVERRIDE_PE3_MPIDR        0x30000
#define PLATFORM_OVERRIDE_PE3_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE3_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE4_INDEX        0x4
#define PLATFORM_OVERRIDE_PE4_MPIDR        0x40000
#define PLATFORM_OVERRIDE_PE4_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE4_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE5_INDEX        0x5
#define PLATFORM_OVERRIDE_PE5_MPIDR        0x50000
#define PLATFORM_OVERRIDE_PE5_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE5_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE6_INDEX        0x6
#define PLATFORM_OVERRIDE_PE6_MPIDR        0x60000
#define PLATFORM_OVERRIDE_PE6_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE6_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE7_INDEX        0x7
#define PLATFORM_OVERRIDE_PE7_MPIDR        0x70000
#define PLATFORM_OVERRIDE_PE7_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE7_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE8_INDEX        0x8
#define PLATFORM_OVERRIDE_PE8_MPIDR        0x80000
#define PLATFORM_OVERRIDE_PE8_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE8_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE9_INDEX        0x9
#define PLATFORM_OVERRIDE_PE9_MPIDR        0x90000
#define PLATFORM_OVERRIDE_PE9_PMU_GSIV     0x17
#define PLATFORM_OVERRIDE_PE9_GMAIN_GSIV   0x19
#define PLATFORM_OVERRIDE_PE10_INDEX       0xA
#define PLATFORM_OVERRIDE_PE10_MPIDR       0xA0000
#define PLATFORM_OVERRIDE_PE10_PMU_GSIV    0x17
#define PLATFORM_OVERRIDE_PE10_GMAIN_GSIV  0x19
#define PLATFORM_OVERRIDE_PE11_INDEX       0xB
#define PLATFORM_OVERRIDE_PE11_MPIDR       0xB0000
#define PLATFORM_OVERRIDE_PE11_PMU_GSIV    0x17
#define PLATFORM_OVERRIDE_PE11_GMAIN_GSIV  0x19
#define PLATFORM_OVERRIDE_PE12_INDEX       0xC
#define PLATFORM_OVERRIDE_PE12_MPIDR       0xC0000
#define PLATFORM_OVERRIDE_PE12_PMU_GSIV    0x17
#define PLATFORM_OVERRIDE_PE12_GMAIN_GSIV  0x19
#define PLATFORM_OVERRIDE_PE13_INDEX       0xD
#define PLATFORM_OVERRIDE_PE13_MPIDR       0xD0000
#define PLATFORM_OVERRIDE_PE13_PMU_GSIV    0x17
#define PLATFORM_OVERRIDE_PE13_GMAIN_GSIV  0x19
#define PLATFORM_OVERRIDE_PE14_INDEX       0xE
#define PLATFORM_OVERRIDE_PE14_MPIDR       0xE0000
#define PLATFORM_OVERRIDE_PE14_PMU_GSIV    0x17
#define PLATFORM_OVERRIDE_PE14_GMAIN_GSIV  0x19
#define PLATFORM_OVERRIDE_PE15_INDEX       0xF
#define PLATFORM_OVERRIDE_PE15_MPIDR       0xF0000
#define PLATFORM_OVERRIDE_PE15_PMU_GSIV    0x17
#define PLATFORM_OVERRIDE_PE15_GMAIN_GSIV  0x19

/* GIC platform config parameters*/
#define PLATFORM_OVERRIDE_GIC_VERSION       0x3
#define PLATFORM_OVERRIDE_CORE_COUNT        0x4
#define PLATFORM_OVERRIDE_CLUSTER_COUNT     0x2
#define PLATFORM_OVERRIDE_GICC_COUNT        16
#define PLATFORM_OVERRIDE_GICD_COUNT        0x1
#define PLATFORM_OVERRIDE_GICRD_COUNT       0x1
#define PLATFORM_OVERRIDE_GICITS_COUNT      0x6
#define PLATFORM_OVERRIDE_GICH_COUNT        0x1
#define PLATFORM_OVERRIDE_GICMSIFRAME_COUNT 0x0
#define PLATFORM_OVERRIDE_GICC_TYPE         0x1000
#define PLATFORM_OVERRIDE_GICD_TYPE         0x1001
#define PLATFORM_OVERRIDE_GICC_GICRD_TYPE   0x1002
#define PLATFORM_OVERRIDE_GICR_GICRD_TYPE   0x1003
#define PLATFORM_OVERRIDE_GICITS_TYPE       0x1004
#define PLATFORM_OVERRIDE_GICMSIFRAME_TYPE  0x1005
#define PLATFORM_OVERRIDE_GICH_TYPE         0x1006
#define PLATFORM_OVERRIDE_GICC_BASE         0x0
#define PLATFORM_OVERRIDE_GICD_BASE         0x30000000
#define PLATFORM_OVERRIDE_GICRD_BASE        0x301C0000
#define PLATFORM_OVERRIDE_GICH_BASE         0x0
#define PLATFORM_OVERRIDE_GICITS0_BASE       0x30040000
#define PLATFORM_OVERRIDE_GICITS0_ID         0
#define PLATFORM_OVERRIDE_GICITS1_BASE       0x30080000
#define PLATFORM_OVERRIDE_GICITS1_ID         0x1
#define PLATFORM_OVERRIDE_GICITS2_BASE       0x300C0000
#define PLATFORM_OVERRIDE_GICITS2_ID         0x2
#define PLATFORM_OVERRIDE_GICITS3_BASE       0x30100000
#define PLATFORM_OVERRIDE_GICITS3_ID         0x3
#define PLATFORM_OVERRIDE_GICITS4_BASE       0x30140000
#define PLATFORM_OVERRIDE_GICITS4_ID         0x4
#define PLATFORM_OVERRIDE_GICITS5_BASE       0x30180000
#define PLATFORM_OVERRIDE_GICITS5_ID         0x5
#define PLATFORM_OVERRIDE_GICIRD_LENGTH     (0x20000*8)

/*
 *Secure EL1 timer Flags, Non-Secure EL1 timer Flags, EL2 timer Flags,
 *and Virtual timer Flags all can have the same definition as follows.
 */
#define INTERRUPT_IS_LEVEL_TRIGGERED 0x0
#define INTERRUPT_IS_EDGE_TRIGGERED  0x1
#define INTERRUPT_IS_ACTIVE_HIGH     0x0
#define INTERRUPT_IS_ACTIVE_LOW      0x1

#define TIMER_MODE      INTERRUPT_IS_LEVEL_TRIGGERED
#define TIMER_POLARITY  INTERRUPT_IS_ACTIVE_LOW

#define TIMER_IS_SECURE     0x1

#define TIMER_IS_ALWAYS_ON_CAPABLE   0x1

/* Timer platform config parameters */
#define PLATFORM_OVERRIDE_S_EL1_TIMER_FLAGS     ((TIMER_POLARITY << 1) | (TIMER_MODE << 0))
#define PLATFORM_OVERRIDE_NS_EL1_TIMER_FLAGS    ((TIMER_POLARITY << 1) | (TIMER_MODE << 0))
#define PLATFORM_OVERRIDE_NS_EL2_TIMER_FLAGS    ((TIMER_POLARITY << 1) | (TIMER_MODE << 0))
#define PLATFORM_OVERRIDE_VIRTUAL_TIMER_FLAGS   ((TIMER_POLARITY << 1) | (TIMER_MODE << 0))
#define PLATFORM_OVERRIDE_S_EL1_TIMER_GSIV      0x1D
#define PLATFORM_OVERRIDE_NS_EL1_TIMER_GSIV     0x1E
#define PLATFORM_OVERRIDE_NS_EL2_TIMER_GSIV     0x1A
#define PLATFORM_OVERRIDE_VIRTUAL_TIMER_GSIV    0x1B
#define PLATFORM_OVERRIDE_EL2_VIR_TIMER_GSIV    0
#define PLATFORM_OVERRIDE_PLATFORM_TIMER_COUNT  0x2

#define PLATFORM_OVERRIDE_SYS_TIMER_TYPE        0x2001
#define PLATFORM_OVERRIDE_TIMER_TYPE            PLATFORM_OVERRIDE_SYS_TIMER_TYPE
#define PLATFORM_OVERRIDE_TIMER_COUNT           0x2
#define PLATFORM_OVERRIDE_TIMER_CNTCTL_BASE     0x2a810000

#define PLATFORM_OVERRIDE_TIMER_CNTBASE_0       0x2a830000
#define PLATFORM_OVERRIDE_TIMER_CNTEL0BASE_0    0xFFFFFFFFFFFFFFFF
#define PLATFORM_OVERRIDE_TIMER_GSIV_0          0x6d
#define PLATFORM_OVERRIDE_TIMER_VIRT_GSIV_0     0x0
#define PLATFORM_OVERRIDE_TIMER_PHY_FLAGS_0     0x0
#define PLATFORM_OVERRIDE_TIMER_VIRT_FLAGS_0    0x0
#define PLATFORM_OVERRIDE_TIMER_CMN_FLAGS_0     ((TIMER_IS_ALWAYS_ON_CAPABLE << 1) | (!TIMER_IS_SECURE << 0))
#define PLATFORM_OVERRIDE_TIMER_FLAGS_0         ((PLATFORM_OVERRIDE_TIMER_CMN_FLAGS_0 << 16) | \
                                                 (PLATFORM_OVERRIDE_TIMER_VIRT_FLAGS_0 << 8) | \
                                                 (PLATFORM_OVERRIDE_TIMER_PHY_FLAGS_0))

#define PLATFORM_OVERRIDE_TIMER_CNTBASE_1       0x2a820000
#define PLATFORM_OVERRIDE_TIMER_CNTEL0BASE_1    0xFFFFFFFFFFFFFFFF
#define PLATFORM_OVERRIDE_TIMER_GSIV_1          0x6c
#define PLATFORM_OVERRIDE_TIMER_VIRT_GSIV_1     0x0
#define PLATFORM_OVERRIDE_TIMER_PHY_FLAGS_1     0x0
#define PLATFORM_OVERRIDE_TIMER_VIRT_FLAGS_1    0x0
#define PLATFORM_OVERRIDE_TIMER_CMN_FLAGS_1     ((TIMER_IS_ALWAYS_ON_CAPABLE << 1) | (TIMER_IS_SECURE << 0))
#define PLATFORM_OVERRIDE_TIMER_FLAGS_1         ((PLATFORM_OVERRIDE_TIMER_CMN_FLAGS_1 << 16) | \
                                                 (PLATFORM_OVERRIDE_TIMER_VIRT_FLAGS_1 << 8) | \
                                                 (PLATFORM_OVERRIDE_TIMER_PHY_FLAGS_1))
#define PLATFORM_OVERRIDE_TIMER_CNTFRQ         0x0
#define PLATFORM_OVERRIDE_TIMEOUT              1
/* Define the Timeout values to be used */
#define PLATFORM_OVERRIDE_TIMEOUT_LARGE         0x100000
#define PLATFORM_OVERRIDE_TIMEOUT_MEDIUM        0x10000
#define PLATFORM_OVERRIDE_TIMEOUT_SMALL         0x100

/* Watchdog platform config parameters */
#define WD_MODE     INTERRUPT_IS_LEVEL_TRIGGERED
#define WD_POLARITY INTERRUPT_IS_ACTIVE_HIGH

#define WD_IS_SECURE     0x1

#define PLATFORM_OVERRIDE_WD_TIMER_COUNT    0x2
#define PLATFORM_OVERRIDE_WD_REFRESH_BASE   0x2A450000
#define PLATFORM_OVERRIDE_WD_CTRL_BASE      0x2A440000
#define PLATFORM_OVERRIDE_WD_GSIV_0         0x6E
#define PLATFORM_OVERRIDE_WD_FLAGS_0        ((!WD_IS_SECURE << 2) | (WD_POLARITY << 1) | (WD_MODE << 0))
#define PLATFORM_OVERRIDE_WD_GSIV_1         0x6F
#define PLATFORM_OVERRIDE_WD_FLAGS_1        ((WD_IS_SECURE << 2) | (WD_POLARITY << 1) | (WD_MODE << 0))


// This value is arbitrary and may have to be adjusted
#define PLATFORM_OVERRIDE_IRQ               1
#define PLATFORM_OVERRIDE_MAX_IRQ_CNT       0xFFFF

#define PLATFORM_OVERRIDE_MAX_SID           20

/* PCIE platform config parameters */
#define PLATFORM_OVERRIDE_NUM_ECAM                1

/* Offset from the memory range to be accesed
 * Modify this macro w.r.t to the requirement */
#define MEM_OFFSET_SMALL   0x10
#define MEM_OFFSET_MEDIUM  0x1000

/* Platform config parameters for ECAM_0 */
#define PLATFORM_OVERRIDE_PCIE_ECAM_BASE_ADDR_0   0x1010000000
#define PLATFORM_OVERRIDE_PCIE_SEGMENT_GRP_NUM_0  0x0
#define PLATFORM_OVERRIDE_PCIE_START_BUS_NUM_0    0x0
#define PLATFORM_OVERRIDE_PCIE_END_BUS_NUM_0      0x3F

#define PLATFORM_OVERRIDE_PCIE_ECAM_BASE_ADDR_1  0x1010000000
#define PLATFORM_OVERRIDE_PCIE_SEGMENT_GRP_NUM_1 0x0
#define PLATFORM_OVERRIDE_PCIE_START_BUS_NUM_1   0x40
#define PLATFORM_OVERRIDE_PCIE_END_BUS_NUM_1     0x7F

#define PLATFORM_OVERRIDE_MAX_BDF           1
#define PLATFORM_OVERRIDE_PCIE_MAX_BUS      0x40
#define PLATFORM_OVERRIDE_PCIE_MAX_DEV      32
#define PLATFORM_OVERRIDE_PCIE_MAX_FUNC     8

/* Sample macros for ECAM_1
 * #define PLATFORM_OVERRIDE_PCIE_ECAM_BASE_ADDR_1  0x00000000
 * #define PLATFORM_OVERRIDE_PCIE_SEGMENT_GRP_NUM_1 0x0
 * #define PLATFORM_OVERRIDE_PCIE_START_BUS_NUM_1   0x0
 * #define PLATFORM_OVERRIDE_PCIE_END_BUS_NUM_1     0x0
 */

/* PCIE device hierarchy table */

#define PLATFORM_PCIE_NUM_ENTRIES        3
#define PLATFORM_PCIE_P2P_NOT_SUPPORTED  1

#define PLATFORM_PCIE_DEV0_CLASSCODE     0x1060101
#define PLATFORM_PCIE_DEV0_VENDOR_ID     0x0ABC
#define PLATFORM_PCIE_DEV0_DEV_ID        0xACED
#define PLATFORM_PCIE_DEV0_BUS_NUM       0
#define PLATFORM_PCIE_DEV0_DEV_NUM       0x1E
#define PLATFORM_PCIE_DEV0_FUNC_NUM      0
#define PLATFORM_PCIE_DEV0_SEG_NUM       0
#define PLATFORM_PCIE_DEV0_DMA_SUPPORT   0
#define PLATFORM_PCIE_DEV0_DMA_COHERENT  0
#define PLATFORM_PCIE_DEV0_P2P_SUPPORT   1
#define PLATFORM_PCIE_DEV0_DMA_64BIT     0
#define PLATFORM_PCIE_DEV0_BEHIND_SMMU   1
#define PLATFORM_PCIE_DEV0_ATC_SUPPORT   0

#define PLATFORM_PCIE_DEV1_CLASSCODE     0xED000000
#define PLATFORM_PCIE_DEV1_VENDOR_ID     0x13B5
#define PLATFORM_PCIE_DEV1_DEV_ID        0xED01
#define PLATFORM_PCIE_DEV1_BUS_NUM       0
#define PLATFORM_PCIE_DEV1_DEV_NUM       0xF
#define PLATFORM_PCIE_DEV1_FUNC_NUM      0
#define PLATFORM_PCIE_DEV1_SEG_NUM       0
#define PLATFORM_PCIE_DEV1_DMA_SUPPORT   0
#define PLATFORM_PCIE_DEV1_DMA_COHERENT  0
#define PLATFORM_PCIE_DEV1_P2P_SUPPORT   1
#define PLATFORM_PCIE_DEV1_DMA_64BIT     0
#define PLATFORM_PCIE_DEV1_BEHIND_SMMU   1
#define PLATFORM_PCIE_DEV1_ATC_SUPPORT   0

#define PLATFORM_PCIE_DEV2_CLASSCODE     0xED000000
#define PLATFORM_PCIE_DEV2_VENDOR_ID     0x13B5
#define PLATFORM_PCIE_DEV2_DEV_ID        0xED01
#define PLATFORM_PCIE_DEV2_BUS_NUM       0
#define PLATFORM_PCIE_DEV2_DEV_NUM       0x1F
#define PLATFORM_PCIE_DEV2_FUNC_NUM      0
#define PLATFORM_PCIE_DEV2_SEG_NUM       0
#define PLATFORM_PCIE_DEV2_DMA_SUPPORT   0
#define PLATFORM_PCIE_DEV2_DMA_COHERENT  0
#define PLATFORM_PCIE_DEV2_P2P_SUPPORT   1
#define PLATFORM_PCIE_DEV2_DMA_64BIT     0
#define PLATFORM_PCIE_DEV2_BEHIND_SMMU   1
#define PLATFORM_PCIE_DEV2_ATC_SUPPORT   0

/* PERIPHERAL platform config parameters */
#define PLATFORM_OVERRIDE_PERIPHERAL_COUNT 3  //UART + USB + SATA

#define UART_ADDRESS                     0xF98DFE18
#define BASE_ADDRESS_ADDRESS_SPACE_ID    0x0
#define BASE_ADDRESS_REGISTER_BIT_WIDTH  0x20
#define BASE_ADDRESS_REGISTER_BIT_OFFSET 0x0
#define BASE_ADDRESS_ADDRESS_SIZE        0x3
#define BASE_ADDRESS_ADDRESS             0x2A400000
#define UART_INTERRUPT_TYPE              8
#define UART_IRQ                         0
#define UART_GLOBAL_SYSTEM_INTERRUPT     0x70
#define UART_PCI_DEVICE_ID               0xFFFF
#define UART_PCI_VENDOR_ID               0xFFFF
#define UART_PCI_BUS_NUMBER              0x0
#define UART_PCI_DEV_NUMBER              0x0
#define UART_PCI_FUNC_NUMBER             0x0
#define UART_PCI_FLAGS                   0x0
#define UART_PCI_SEGMENT                 0x0

/* IOVIRT platform config parameters */
#define IOVIRT_ADDRESS                0xF981EB18
#define IORT_NODE_COUNT               13
#define NUM_ITS_COUNT                 5
#define IOVIRT_ITS_COUNT              1
#define IOVIRT_SMMUV3_COUNT           5
#define IOVIRT_RC_COUNT               1
#define IOVIRT_SMMUV2_COUNT           0
#define IOVIRT_NAMED_COMPONENT_COUNT  2
#define IOVIRT_PMCG_COUNT             0
#define IOVIRT_SMMUV3_0_BASE_ADDRESS  0x40000000
#define IOVIRT_SMMUV3_1_BASE_ADDRESS  0x42000000
#define IOVIRT_SMMUV3_2_BASE_ADDRESS  0x44000000
#define IOVIRT_SMMUV3_3_BASE_ADDRESS  0x46000000
#define IOVIRT_SMMUV3_4_BASE_ADDRESS  0x48000000
#define IOVIRT_SMMU_CTX_INT_OFFSET    0x0
#define IOVIRT_SMMU_CTX_INT_CNT       0x0
#define IOVIRT_RC_PCI_SEG_NUM         0x0
#define IOVIRT_RC_MEMORY_PROPERTIES   0x1
#define IOVIRT_RC_ATS_ATTRIBUTE       0x1

#define RC_MAP0_INPUT_BASE            0x0
#define RC_MAP0_ID_COUNT              0x3FFF
#define RC_MAP0_OUTPUT_BASE           0x30000
#define RC_MAP0_OUTPUT_REF            0x5A4
#define RC_MAP1_INPUT_BASE            0x4000
#define RC_MAP1_ID_COUNT              0x3FFF
#define RC_MAP1_OUTPUT_BASE           0x34000
#define RC_MAP1_OUTPUT_REF            0x6D0
#define RC_MAP2_INPUT_BASE            0x8000
#define RC_MAP2_ID_COUNT              0x3FFF
#define RC_MAP2_OUTPUT_BASE           0x38000
#define RC_MAP2_OUTPUT_REF            0x7FC
#define RC_MAP3_INPUT_BASE            0xC000
#define RC_MAP3_ID_COUNT              0x3FFF
#define RC_MAP3_OUTPUT_BASE           0x3C000
#define RC_MAP3_OUTPUT_REF            0x928

#define SMMUV3_0_ID_MAP0_INPUT_BASE   0x30000
#define SMMUV3_0_ID_MAP0_ID_COUNT     0x3FFF
#define SMMUV3_0_ID_MAP0_OUTPUT_BASE  0x30000
#define SMMUV3_0_ID_MAP0_OUTPUT_REF   0x18
#define SMMUV3_0_ID_MAP1_INPUT_BASE   0x0
#define SMMUV3_0_ID_MAP1_ID_COUNT     0x1
#define SMMUV3_0_ID_MAP1_OUTPUT_BASE  0x80000
#define SMMUV3_0_ID_MAP1_OUTPUT_REF   0x18

#define SMMUV3_1_ID_MAP0_INPUT_BASE   0x34000
#define SMMUV3_1_ID_MAP0_ID_COUNT     0x3FFF
#define SMMUV3_1_ID_MAP0_OUTPUT_BASE  0x34000
#define SMMUV3_1_ID_MAP0_OUTPUT_REF   0x134
#define SMMUV3_1_ID_MAP1_INPUT_BASE   0x0
#define SMMUV3_1_ID_MAP1_ID_COUNT     0x1
#define SMMUV3_1_ID_MAP1_OUTPUT_BASE  0x80000
#define SMMUV3_1_ID_MAP1_OUTPUT_REF   0x134

#define SMMUV3_2_ID_MAP0_INPUT_BASE   0x38000
#define SMMUV3_2_ID_MAP0_ID_COUNT     0x3FFF
#define SMMUV3_2_ID_MAP0_OUTPUT_BASE  0x38000
#define SMMUV3_2_ID_MAP0_OUTPUT_REF   0x250
#define SMMUV3_2_ID_MAP1_INPUT_BASE   0x0
#define SMMUV3_2_ID_MAP1_ID_COUNT     0x1
#define SMMUV3_2_ID_MAP1_OUTPUT_BASE  0x80000
#define SMMUV3_2_ID_MAP1_OUTPUT_REF   0x250

#define SMMUV3_3_ID_MAP0_INPUT_BASE   0x3C000
#define SMMUV3_3_ID_MAP0_ID_COUNT     0x3FFF
#define SMMUV3_3_ID_MAP0_OUTPUT_BASE  0x3C000
#define SMMUV3_3_ID_MAP0_OUTPUT_REF   0x36C
#define SMMUV3_3_ID_MAP1_INPUT_BASE   0x0
#define SMMUV3_3_ID_MAP1_ID_COUNT     0x1
#define SMMUV3_3_ID_MAP1_OUTPUT_BASE  0x80000
#define SMMUV3_3_ID_MAP1_OUTPUT_REF   0x36C

#define SMMUV3_4_ID_MAP0_INPUT_BASE   0x10000
#define SMMUV3_4_ID_MAP0_ID_COUNT     0x9
#define SMMUV3_4_ID_MAP0_OUTPUT_BASE  0x10000
#define SMMUV3_4_ID_MAP0_OUTPUT_REF   0x488
#define SMMUV3_4_ID_MAP1_INPUT_BASE   0x30000
#define SMMUV3_4_ID_MAP1_ID_COUNT     0x9
#define SMMUV3_4_ID_MAP1_OUTPUT_BASE  0x30000
#define SMMUV3_4_ID_MAP1_OUTPUT_REF   0x488
#define SMMUV3_4_ID_MAP2_INPUT_BASE   0x0
#define SMMUV3_4_ID_MAP2_ID_COUNT     0x1
#define SMMUV3_4_ID_MAP2_OUTPUT_BASE  0x80000
#define SMMUV3_4_ID_MAP2_OUTPUT_REF   0x488

#define NAMED_COMP0_MAP0_INPUT_BASE   0x0
#define NAMED_COMP0_MAP0_ID_COUNT     0x1
#define NAMED_COMP0_MAP0_OUTPUT_BASE  0x10000
#define NAMED_COMP0_MAP0_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP1_INPUT_BASE   0x1
#define NAMED_COMP0_MAP1_ID_COUNT     0x1
#define NAMED_COMP0_MAP1_OUTPUT_BASE  0x10001
#define NAMED_COMP0_MAP1_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP2_INPUT_BASE   0x2
#define NAMED_COMP0_MAP2_ID_COUNT     0x1
#define NAMED_COMP0_MAP2_OUTPUT_BASE  0x10002
#define NAMED_COMP0_MAP2_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP3_INPUT_BASE   0x3
#define NAMED_COMP0_MAP3_ID_COUNT     0x1
#define NAMED_COMP0_MAP3_OUTPUT_BASE  0x10003
#define NAMED_COMP0_MAP3_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP4_INPUT_BASE   0x4
#define NAMED_COMP0_MAP4_ID_COUNT     0x1
#define NAMED_COMP0_MAP4_OUTPUT_BASE  0x10004
#define NAMED_COMP0_MAP4_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP5_INPUT_BASE   0x5
#define NAMED_COMP0_MAP5_ID_COUNT     0x1
#define NAMED_COMP0_MAP5_OUTPUT_BASE  0x10005
#define NAMED_COMP0_MAP5_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP6_INPUT_BASE   0x6
#define NAMED_COMP0_MAP6_ID_COUNT     0x1
#define NAMED_COMP0_MAP6_OUTPUT_BASE  0x10006
#define NAMED_COMP0_MAP6_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP7_INPUT_BASE   0x7
#define NAMED_COMP0_MAP7_ID_COUNT     0x1
#define NAMED_COMP0_MAP7_OUTPUT_BASE  0x10007
#define NAMED_COMP0_MAP7_OUTPUT_REF   0xA54
#define NAMED_COMP0_MAP8_INPUT_BASE   0x8
#define NAMED_COMP0_MAP8_ID_COUNT     0x1
#define NAMED_COMP0_MAP8_OUTPUT_BASE  0x10008
#define NAMED_COMP0_MAP8_OUTPUT_REF   0xA54


#define NAMED_COMP1_MAP0_INPUT_BASE   0x0
#define NAMED_COMP1_MAP0_ID_COUNT     0x1
#define NAMED_COMP1_MAP0_OUTPUT_BASE  0x30000
#define NAMED_COMP1_MAP0_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP1_INPUT_BASE   0x1
#define NAMED_COMP1_MAP1_ID_COUNT     0x1
#define NAMED_COMP1_MAP1_OUTPUT_BASE  0x30001
#define NAMED_COMP1_MAP1_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP2_INPUT_BASE   0x2
#define NAMED_COMP1_MAP2_ID_COUNT     0x1
#define NAMED_COMP1_MAP2_OUTPUT_BASE  0x30002
#define NAMED_COMP1_MAP2_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP3_INPUT_BASE   0x3
#define NAMED_COMP1_MAP3_ID_COUNT     0x1
#define NAMED_COMP1_MAP3_OUTPUT_BASE  0x30003
#define NAMED_COMP1_MAP3_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP4_INPUT_BASE   0x4
#define NAMED_COMP1_MAP4_ID_COUNT     0x1
#define NAMED_COMP1_MAP4_OUTPUT_BASE  0x30004
#define NAMED_COMP1_MAP4_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP5_INPUT_BASE   0x5
#define NAMED_COMP1_MAP5_ID_COUNT     0x1
#define NAMED_COMP1_MAP5_OUTPUT_BASE  0x30005
#define NAMED_COMP1_MAP5_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP6_INPUT_BASE   0x6
#define NAMED_COMP1_MAP6_ID_COUNT     0x1
#define NAMED_COMP1_MAP6_OUTPUT_BASE  0x30006
#define NAMED_COMP1_MAP6_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP7_INPUT_BASE   0x7
#define NAMED_COMP1_MAP7_ID_COUNT     0x1
#define NAMED_COMP1_MAP7_OUTPUT_BASE  0x30007
#define NAMED_COMP1_MAP7_OUTPUT_REF   0xA54
#define NAMED_COMP1_MAP8_INPUT_BASE   0x8
#define NAMED_COMP1_MAP8_ID_COUNT     0x1
#define NAMED_COMP1_MAP8_OUTPUT_BASE  0x30008
#define NAMED_COMP1_MAP8_OUTPUT_REF   0xA54

#define IOVIRT_PMCG_0_BASE_ADDRESS      0x0
#define IOVIRT_PMCG_0_OVERFLOW_GSIV     0x0
#define IOVIRT_PMCG_0_NODE_REFERENCE    0x0
#define IOVIRT_PMCG_0_SMMU_BASE         0x0

#define IOVIRT_NAMED_0_SMMU_BASE      0x48000000
#define IOVIRT_NAMED_0_MEM_PROP       0x1
#define IOVIRT_NAMED_0_DEVICE_NAME    "\\_SB_.ETR0"
#define IOVIRT_NAMED_1_SMMU_BASE      0x48000000
#define IOVIRT_NAMED_1_MEM_PROP       0x1
#define IOVIRT_NAMED_1_DEVICE_NAME    "\\_SB_.DMA0"

#define IOVIRT_RC_NUM_MAP             4
#define IOVIRT_SMMUV3_0_NUM_MAP       2
#define IOVIRT_SMMUV3_1_NUM_MAP       2
#define IOVIRT_SMMUV3_2_NUM_MAP       2
#define IOVIRT_SMMUV3_3_NUM_MAP       2
#define IOVIRT_SMMUV3_4_NUM_MAP       3
#define IOVIRT_NAMED_COMP0_NUM_MAP    9
#define IOVIRT_NAMED_COMP1_NUM_MAP    9
#define IOVIRT_MAX_NUM_MAP            33

/* Coresight components config parameters*/
#define CS_COMPONENT_COUNT         1

#define CS_COMPONENT_0_IDENTIFIER    "ARMHC97C"
#define CS_COMPONENT_0_DEVICE_NAME   "\\_SB_.ETR0"

/* DMA platform config parameters */
#define PLATFORM_OVERRIDE_DMA_CNT   0

/*Exerciser platform config details*/
#define TEST_REG_COUNT              10
#define EXERCISER_ID                0xED0113B5
#define PCIE_CAP_CTRL_OFFSET        0x4// offset from the extended capability header

/* Exerciser MMIO Offsets */
#define INTXCTL         0x004
#define MSICTL          0x000
#define DMACTL1         0x08
#define DMA_BUS_ADDR    0x010
#define DMA_LEN         0x018
#define DMASTATUS       0x01C
#define PCI_MAX_BUS     255
#define PCI_MAX_DEVICE  31
#define PASID_VAL       0x020
#define ATSCTL          0x024
#define TXN_TRACE     0x40
#define TXN_CTRL_BASE 0x44
#define ATS_ADDR        0x028

#define DVSEC_CTRL     0x8
#define PCI_EXT_CAP_ID  0x10
#define PASID           0x1B
#define PCIE            0x1
#define PCI             0x0
#define DVSEC          0x0023
#define AER            0x0001

/* PCI/PCIe express extended capability structure's
   next capability pointer mask and cap ID mask */
#define PCIE_NXT_CAP_PTR_MASK 0x0FFF
#define PCIE_CAP_ID_MASK      0xFFFF
#define PCI_CAP_ID_MASK       0x00FF
#define PCI_NXT_CAP_PTR_MASK  0x00FF
#define CAP_PTR_MASK          0x00FF

#define CLR_INTR_MASK       0xFFFFFFFE
#define PASID_TLP_STOP_MASK 0xFFFFFFBF
#define PASID_VAL_MASK      ((0x1ul << 20) - 1)
#define PASID_VAL_SHIFT     12
#define PASID_LEN_SHIFT     7
#define PASID_LEN_MASK      0x7ul
#define PASID_EN_SHIFT      6
#define DMA_TO_DEVICE_MASK  0xFFFFFFEF

/* shift_bit */
#define SHIFT_1BIT             1
#define SHIFT_2BIT             2
#define SHIFT_4BIT             4
#define SHITT_8BIT             8
#define MASK_BIT               1
#define PREFETCHABLE_BIT_SHIFT 3
#define ERR_CODE_SHIFT         20
#define FATAL_SHIFT            31
#define ERROR_INJECT_BIT       17

#define PCI_CAP_PTR_OFFSET     8
#define PCIE_CAP_PTR_OFFSET    20

#define MSI_GENERATION_MASK (1 << 31)

#define NO_SNOOP_START_MASK 0x20
#define NO_SNOOP_STOP_MASK  0xFFFFFFDF
#define PCIE_CAP_DIS_MASK   0xFFFEFFFF
#define PCIE_CAP_EN_MASK    (1 << 16)
#define PASID_EN_MASK       (1 << 6)

/* PCIe Config space Offset */
#define BAR0_OFFSET         0x10
#define COMMAND_REG_OFFSET  0x04
#define CAP_PTR_OFFSET      0x34
#define PCIE_CAP_OFFSET     0x100


#define RID_CTL_REG    0x3C
#define RID_VALUE_MASK 0xFFFF
#define RID_VALID_MASK (1ul << 31)
#define RID_VALID      1
#define RID_NOT_VALID  0
#define ATS_TRIGGER    1
#define ATS_STATUS     (1ul << 7)
#define TXN_INVALID    0xFFFFFFFF
#define TXN_START      1
#define TXN_STOP       0

#define PCIE_CAP_CTRL_OFFSET  0x4// offset from the extended capability header

/* Memory config */
#define PLATFORM_OVERRIDE_MEMORY_ENTRY_COUNT        0x3
#define PLATFORM_OVERRIDE_MEMORY_ENTRY0_PHY_ADDR    0xC000000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY0_VIRT_ADDR   0xC000000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY0_SIZE        0x4000000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY0_TYPE        MEMORY_TYPE_DEVICE
#define PLATFORM_OVERRIDE_MEMORY_ENTRY1_PHY_ADDR    0xFF600000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY1_VIRT_ADDR   0xFF600000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY1_SIZE        0x10000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY1_TYPE        MEMORY_TYPE_RESERVED
#define PLATFORM_OVERRIDE_MEMORY_ENTRY2_PHY_ADDR    0x80000000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY2_VIRT_ADDR   0x80000000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY2_SIZE        0x7F000000
#define PLATFORM_OVERRIDE_MEMORY_ENTRY2_TYPE        MEMORY_TYPE_NORMAL

/* Cache config and MASKS*/
#define SIZE_MASK           0x1
#define CACHE_TYPE_MASK     0x10
#define CACHE_ID_MASK       0x80
#define CACHE_TYPE_SHIFT    4
#define CACHE_ID_SHIFT      7

#define DEFAULT_CACHE_IDX 0xFFFFFFFF
#define MAX_L1_CACHE_RES 2 /* Generally PE Level 1 have a data and a instruction cache */

#define PLATFORM_OVERRIDE_CACHE_CNT            0x30

#define PLATFORM_CACHE0_FLAGS                  0xFF
#define PLATFORM_CACHE0_OFFSET                 0x68
#define PLATFORM_CACHE0_NEXT_LEVEL_INDEX       1
#define PLATFORM_CACHE0_SIZE                   0x10000
#define PLATFORM_CACHE0_CACHE_ID               0x1
#define PLATFORM_CACHE0_IS_PRIVATE             0x1
#define PLATFORM_CACHE0_TYPE                   0

#define PLATFORM_CACHE1_FLAGS                  0xFF
#define PLATFORM_CACHE1_OFFSET                 0xA0
#define PLATFORM_CACHE1_NEXT_LEVEL_INDEX       -1
#define PLATFORM_CACHE1_SIZE                   0x100000
#define PLATFORM_CACHE1_CACHE_ID               0x3
#define PLATFORM_CACHE1_IS_PRIVATE             0x1
#define PLATFORM_CACHE1_TYPE                   0x2

#define PLATFORM_CACHE2_FLAGS                  0xFF
#define PLATFORM_CACHE2_OFFSET                 0x84
#define PLATFORM_CACHE2_NEXT_LEVEL_INDEX       0x1
#define PLATFORM_CACHE2_SIZE                   0x10000
#define PLATFORM_CACHE2_CACHE_ID               0x2
#define PLATFORM_CACHE2_IS_PRIVATE             0x1
#define PLATFORM_CACHE2_TYPE                   0x1

#define PLATFORM_CACHE3_FLAGS                  0xFF
#define PLATFORM_CACHE3_OFFSET                 0xEC
#define PLATFORM_CACHE3_NEXT_LEVEL_INDEX       4
#define PLATFORM_CACHE3_SIZE                   0x10000
#define PLATFORM_CACHE3_CACHE_ID               0x1001
#define PLATFORM_CACHE3_IS_PRIVATE             0x1
#define PLATFORM_CACHE3_TYPE                   0x0

#define PLATFORM_CACHE4_FLAGS                  0xFF
#define PLATFORM_CACHE4_OFFSET                 0x124
#define PLATFORM_CACHE4_NEXT_LEVEL_INDEX       -1
#define PLATFORM_CACHE4_SIZE                   0x100000
#define PLATFORM_CACHE4_CACHE_ID               0x1003
#define PLATFORM_CACHE4_IS_PRIVATE             0x1
#define PLATFORM_CACHE4_TYPE                   0x2

#define PLATFORM_CACHE5_FLAGS                  0xFF
#define PLATFORM_CACHE5_OFFSET                 0x108
#define PLATFORM_CACHE5_NEXT_LEVEL_INDEX       4
#define PLATFORM_CACHE5_SIZE                   0x10000
#define PLATFORM_CACHE5_CACHE_ID               0x1002
#define PLATFORM_CACHE5_IS_PRIVATE             0x1
#define PLATFORM_CACHE5_TYPE                   0x1

#define PLATFORM_CACHE6_FLAGS                  0xFF
#define PLATFORM_CACHE6_OFFSET                 0x170
#define PLATFORM_CACHE6_NEXT_LEVEL_INDEX       7
#define PLATFORM_CACHE6_SIZE                   0x10000
#define PLATFORM_CACHE6_CACHE_ID               0x2001
#define PLATFORM_CACHE6_IS_PRIVATE             0x1
#define PLATFORM_CACHE6_TYPE                   0x0

#define PLATFORM_CACHE7_FLAGS                  0xFF
#define PLATFORM_CACHE7_OFFSET                 0x1A8
#define PLATFORM_CACHE7_NEXT_LEVEL_INDEX       -1
#define PLATFORM_CACHE7_SIZE                   0x100000
#define PLATFORM_CACHE7_CACHE_ID               0x2003
#define PLATFORM_CACHE7_IS_PRIVATE             0x1
#define PLATFORM_CACHE7_TYPE                   0x2

#define PLATFORM_CACHE8_FLAGS                  0xFF
#define PLATFORM_CACHE8_OFFSET                 0x18C
#define PLATFORM_CACHE8_NEXT_LEVEL_INDEX       7
#define PLATFORM_CACHE8_SIZE                   0x10000
#define PLATFORM_CACHE8_CACHE_ID               0x2002
#define PLATFORM_CACHE8_IS_PRIVATE             0x1
#define PLATFORM_CACHE8_TYPE                   0x1

#define PLATFORM_CACHE9_FLAGS                  0xFF
#define PLATFORM_CACHE9_OFFSET                 0x1f4
#define PLATFORM_CACHE9_NEXT_LEVEL_INDEX       10
#define PLATFORM_CACHE9_SIZE                   0x10000
#define PLATFORM_CACHE9_CACHE_ID               0x3001
#define PLATFORM_CACHE9_IS_PRIVATE             0x1
#define PLATFORM_CACHE9_TYPE                   0x0

#define PLATFORM_CACHE10_FLAGS                 0xFF
#define PLATFORM_CACHE10_OFFSET                0x22c
#define PLATFORM_CACHE10_NEXT_LEVEL_INDEX     -1
#define PLATFORM_CACHE10_SIZE                  0x100000
#define PLATFORM_CACHE10_CACHE_ID              0x3003
#define PLATFORM_CACHE10_IS_PRIVATE            0x1
#define PLATFORM_CACHE10_TYPE                  0x2

#define PLATFORM_CACHE11_FLAGS                 0xFF
#define PLATFORM_CACHE11_OFFSET                0x210
#define PLATFORM_CACHE11_NEXT_LEVEL_INDEX      10
#define PLATFORM_CACHE11_SIZE                  0x10000
#define PLATFORM_CACHE11_CACHE_ID              0x3002
#define PLATFORM_CACHE11_IS_PRIVATE            0x1
#define PLATFORM_CACHE11_TYPE                  0x1

#define PLATFORM_CACHE12_FLAGS                 0xFF
#define PLATFORM_CACHE12_OFFSET                0x278
#define PLATFORM_CACHE12_NEXT_LEVEL_INDEX      13
#define PLATFORM_CACHE12_SIZE                  0x10000
#define PLATFORM_CACHE12_CACHE_ID              0x4001
#define PLATFORM_CACHE12_IS_PRIVATE            0x1
#define PLATFORM_CACHE12_TYPE                  0x0

#define PLATFORM_CACHE13_FLAGS                 0xFF
#define PLATFORM_CACHE13_OFFSET                0x2b0
#define PLATFORM_CACHE13_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE13_SIZE                  0x100000
#define PLATFORM_CACHE13_CACHE_ID              0x4003
#define PLATFORM_CACHE13_IS_PRIVATE            0x1
#define PLATFORM_CACHE13_TYPE                  0x2

#define PLATFORM_CACHE14_FLAGS                 0xFF
#define PLATFORM_CACHE14_OFFSET                0x294
#define PLATFORM_CACHE14_NEXT_LEVEL_INDEX      13
#define PLATFORM_CACHE14_SIZE                  0x10000
#define PLATFORM_CACHE14_CACHE_ID              0x4002
#define PLATFORM_CACHE14_IS_PRIVATE            0x1
#define PLATFORM_CACHE14_TYPE                  0x1

#define PLATFORM_CACHE15_FLAGS                 0xFF
#define PLATFORM_CACHE15_OFFSET                0x2fc
#define PLATFORM_CACHE15_NEXT_LEVEL_INDEX      16
#define PLATFORM_CACHE15_SIZE                  0x10000
#define PLATFORM_CACHE15_CACHE_ID              0x5001
#define PLATFORM_CACHE15_IS_PRIVATE            0x1
#define PLATFORM_CACHE15_TYPE                  0x0

#define PLATFORM_CACHE16_FLAGS                 0xFF
#define PLATFORM_CACHE16_OFFSET                0x334
#define PLATFORM_CACHE16_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE16_SIZE                  0x100000
#define PLATFORM_CACHE16_CACHE_ID              0x5003
#define PLATFORM_CACHE16_IS_PRIVATE            0x1
#define PLATFORM_CACHE16_TYPE                  0x2

#define PLATFORM_CACHE17_FLAGS                 0xFF
#define PLATFORM_CACHE17_OFFSET                0x318
#define PLATFORM_CACHE17_NEXT_LEVEL_INDEX      16
#define PLATFORM_CACHE17_SIZE                  0x10000
#define PLATFORM_CACHE17_CACHE_ID              0x5002
#define PLATFORM_CACHE17_IS_PRIVATE            0x1
#define PLATFORM_CACHE17_TYPE                  0x1

#define PLATFORM_CACHE18_FLAGS                 0xFF
#define PLATFORM_CACHE18_OFFSET                0x380
#define PLATFORM_CACHE18_NEXT_LEVEL_INDEX      19
#define PLATFORM_CACHE18_SIZE                  0x10000
#define PLATFORM_CACHE18_CACHE_ID              0x6001
#define PLATFORM_CACHE18_IS_PRIVATE            0x1
#define PLATFORM_CACHE18_TYPE                  0x0

#define PLATFORM_CACHE19_FLAGS                 0xFF
#define PLATFORM_CACHE19_OFFSET                0x3b8
#define PLATFORM_CACHE19_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE19_SIZE                  0x100000
#define PLATFORM_CACHE19_CACHE_ID              0x6003
#define PLATFORM_CACHE19_IS_PRIVATE            0x1
#define PLATFORM_CACHE19_TYPE                  0x2

#define PLATFORM_CACHE20_FLAGS                 0xFF
#define PLATFORM_CACHE20_OFFSET                0x39c
#define PLATFORM_CACHE20_NEXT_LEVEL_INDEX      19
#define PLATFORM_CACHE20_SIZE                  0x10000
#define PLATFORM_CACHE20_CACHE_ID              0x6002
#define PLATFORM_CACHE20_IS_PRIVATE            0x1
#define PLATFORM_CACHE20_TYPE                  0x1

#define PLATFORM_CACHE21_FLAGS                 0xFF
#define PLATFORM_CACHE21_OFFSET                0x404
#define PLATFORM_CACHE21_NEXT_LEVEL_INDEX      22
#define PLATFORM_CACHE21_SIZE                  0x10000
#define PLATFORM_CACHE21_CACHE_ID              0x7001
#define PLATFORM_CACHE21_IS_PRIVATE            0x1
#define PLATFORM_CACHE21_TYPE                  0x0

#define PLATFORM_CACHE22_FLAGS                 0xFF
#define PLATFORM_CACHE22_OFFSET                0x43c
#define PLATFORM_CACHE22_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE22_SIZE                  0x100000
#define PLATFORM_CACHE22_CACHE_ID              0x7003
#define PLATFORM_CACHE22_IS_PRIVATE            0x1
#define PLATFORM_CACHE22_TYPE                  0x2

#define PLATFORM_CACHE23_FLAGS                 0xFF
#define PLATFORM_CACHE23_OFFSET                0x420
#define PLATFORM_CACHE23_NEXT_LEVEL_INDEX      22
#define PLATFORM_CACHE23_SIZE                  0x10000
#define PLATFORM_CACHE23_CACHE_ID              0x7002
#define PLATFORM_CACHE23_IS_PRIVATE            0x1
#define PLATFORM_CACHE23_TYPE                  0x1

#define PLATFORM_CACHE24_FLAGS                 0xFF
#define PLATFORM_CACHE24_OFFSET                0x488
#define PLATFORM_CACHE24_NEXT_LEVEL_INDEX      25
#define PLATFORM_CACHE24_SIZE                  0x10000
#define PLATFORM_CACHE24_CACHE_ID              0x8001
#define PLATFORM_CACHE24_IS_PRIVATE            0x1
#define PLATFORM_CACHE24_TYPE                  0x0

#define PLATFORM_CACHE25_FLAGS                 0xFF
#define PLATFORM_CACHE25_OFFSET                0x4c0
#define PLATFORM_CACHE25_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE25_SIZE                  0x100000
#define PLATFORM_CACHE25_CACHE_ID              0x8003
#define PLATFORM_CACHE25_IS_PRIVATE            0x1
#define PLATFORM_CACHE25_TYPE                  0x2

#define PLATFORM_CACHE26_FLAGS                 0xFF
#define PLATFORM_CACHE26_OFFSET                0x4a4
#define PLATFORM_CACHE26_NEXT_LEVEL_INDEX      25
#define PLATFORM_CACHE26_SIZE                  0x10000
#define PLATFORM_CACHE26_CACHE_ID              0x8002
#define PLATFORM_CACHE26_IS_PRIVATE            0x1
#define PLATFORM_CACHE26_TYPE                  0x1

#define PLATFORM_CACHE27_FLAGS                 0xFF
#define PLATFORM_CACHE27_OFFSET                0x50c
#define PLATFORM_CACHE27_NEXT_LEVEL_INDEX      28
#define PLATFORM_CACHE27_SIZE                  0x10000
#define PLATFORM_CACHE27_CACHE_ID              0x9001
#define PLATFORM_CACHE27_IS_PRIVATE            0x1
#define PLATFORM_CACHE27_TYPE                  0x0

#define PLATFORM_CACHE28_FLAGS                 0xFF
#define PLATFORM_CACHE28_OFFSET                0x544
#define PLATFORM_CACHE28_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE28_SIZE                  0x100000
#define PLATFORM_CACHE28_CACHE_ID              0x9003
#define PLATFORM_CACHE28_IS_PRIVATE            0x1
#define PLATFORM_CACHE28_TYPE                  0x2

#define PLATFORM_CACHE29_FLAGS                 0xFF
#define PLATFORM_CACHE29_OFFSET                0x528
#define PLATFORM_CACHE29_NEXT_LEVEL_INDEX      28
#define PLATFORM_CACHE29_SIZE                  0x10000
#define PLATFORM_CACHE29_CACHE_ID              0x9002
#define PLATFORM_CACHE29_IS_PRIVATE            0x1
#define PLATFORM_CACHE29_TYPE                  0x1

#define PLATFORM_CACHE30_FLAGS                 0xFF
#define PLATFORM_CACHE30_OFFSET                0x590
#define PLATFORM_CACHE30_NEXT_LEVEL_INDEX      31
#define PLATFORM_CACHE30_SIZE                  0x10000
#define PLATFORM_CACHE30_CACHE_ID              0xa001
#define PLATFORM_CACHE30_IS_PRIVATE            0x1
#define PLATFORM_CACHE30_TYPE                  0x0

#define PLATFORM_CACHE31_FLAGS                 0xFF
#define PLATFORM_CACHE31_OFFSET                0x5c8
#define PLATFORM_CACHE31_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE31_SIZE                  0x100000
#define PLATFORM_CACHE31_CACHE_ID              0xa003
#define PLATFORM_CACHE31_IS_PRIVATE            0x1
#define PLATFORM_CACHE31_TYPE                  0x2

#define PLATFORM_CACHE32_FLAGS                 0xFF
#define PLATFORM_CACHE32_OFFSET                0x5ac
#define PLATFORM_CACHE32_NEXT_LEVEL_INDEX      31
#define PLATFORM_CACHE32_SIZE                  0x10000
#define PLATFORM_CACHE32_CACHE_ID              0xa002
#define PLATFORM_CACHE32_IS_PRIVATE            0x1
#define PLATFORM_CACHE32_TYPE                  0x1

#define PLATFORM_CACHE33_FLAGS                 0xFF
#define PLATFORM_CACHE33_OFFSET                0x614
#define PLATFORM_CACHE33_NEXT_LEVEL_INDEX      34
#define PLATFORM_CACHE33_SIZE                  0x10000
#define PLATFORM_CACHE33_CACHE_ID              0xb001
#define PLATFORM_CACHE33_IS_PRIVATE            0x1
#define PLATFORM_CACHE33_TYPE                  0x0

#define PLATFORM_CACHE34_FLAGS                 0xFF
#define PLATFORM_CACHE34_OFFSET                0x64c
#define PLATFORM_CACHE34_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE34_SIZE                  0x100000
#define PLATFORM_CACHE34_CACHE_ID              0xb003
#define PLATFORM_CACHE34_IS_PRIVATE            0x1
#define PLATFORM_CACHE34_TYPE                  0x2

#define PLATFORM_CACHE35_FLAGS                 0xFF
#define PLATFORM_CACHE35_OFFSET                0x630
#define PLATFORM_CACHE35_NEXT_LEVEL_INDEX      34
#define PLATFORM_CACHE35_SIZE                  0x10000
#define PLATFORM_CACHE35_CACHE_ID              0xb002
#define PLATFORM_CACHE35_IS_PRIVATE            0x1
#define PLATFORM_CACHE35_TYPE                  0x1

#define PLATFORM_CACHE36_FLAGS                 0xFF
#define PLATFORM_CACHE36_OFFSET                0x698
#define PLATFORM_CACHE36_NEXT_LEVEL_INDEX      37
#define PLATFORM_CACHE36_SIZE                  0x10000
#define PLATFORM_CACHE36_CACHE_ID              0xc001
#define PLATFORM_CACHE36_IS_PRIVATE            0x1
#define PLATFORM_CACHE36_TYPE                  0x0

#define PLATFORM_CACHE37_FLAGS                 0xFF
#define PLATFORM_CACHE37_OFFSET                0x6d0
#define PLATFORM_CACHE37_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE37_SIZE                  0x100000
#define PLATFORM_CACHE37_CACHE_ID              0xc003
#define PLATFORM_CACHE37_IS_PRIVATE            0x1
#define PLATFORM_CACHE37_TYPE                  0x2

#define PLATFORM_CACHE38_FLAGS                 0xFF
#define PLATFORM_CACHE38_OFFSET                0x6b4
#define PLATFORM_CACHE38_NEXT_LEVEL_INDEX      37
#define PLATFORM_CACHE38_SIZE                  0x10000
#define PLATFORM_CACHE38_CACHE_ID              0xc002
#define PLATFORM_CACHE38_IS_PRIVATE            0x1
#define PLATFORM_CACHE38_TYPE                  0x1

#define PLATFORM_CACHE39_FLAGS                 0xFF
#define PLATFORM_CACHE39_OFFSET                0x71c
#define PLATFORM_CACHE39_NEXT_LEVEL_INDEX      40
#define PLATFORM_CACHE39_SIZE                  0x10000
#define PLATFORM_CACHE39_CACHE_ID              0xd001
#define PLATFORM_CACHE39_IS_PRIVATE            0x1
#define PLATFORM_CACHE39_TYPE                  0x0

#define PLATFORM_CACHE40_FLAGS                 0xFF
#define PLATFORM_CACHE40_OFFSET                0x754
#define PLATFORM_CACHE40_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE40_SIZE                  0x100000
#define PLATFORM_CACHE40_CACHE_ID              0xd003
#define PLATFORM_CACHE40_IS_PRIVATE            0x1
#define PLATFORM_CACHE40_TYPE                  0x2

#define PLATFORM_CACHE41_FLAGS                 0xFF
#define PLATFORM_CACHE41_OFFSET                0x738
#define PLATFORM_CACHE41_NEXT_LEVEL_INDEX      40
#define PLATFORM_CACHE41_SIZE                  0x10000
#define PLATFORM_CACHE41_CACHE_ID              0xd002
#define PLATFORM_CACHE41_IS_PRIVATE            0x1
#define PLATFORM_CACHE41_TYPE                  0x1

#define PLATFORM_CACHE42_FLAGS                 0xFF
#define PLATFORM_CACHE42_OFFSET                0x7a0
#define PLATFORM_CACHE42_NEXT_LEVEL_INDEX      43
#define PLATFORM_CACHE42_SIZE                  0x10000
#define PLATFORM_CACHE42_CACHE_ID              0xe001
#define PLATFORM_CACHE42_IS_PRIVATE            0x1
#define PLATFORM_CACHE42_TYPE                  0x0

#define PLATFORM_CACHE43_FLAGS                 0xFF
#define PLATFORM_CACHE43_OFFSET                0x7d8
#define PLATFORM_CACHE43_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE43_SIZE                  0x100000
#define PLATFORM_CACHE43_CACHE_ID              0xe003
#define PLATFORM_CACHE43_IS_PRIVATE            0x1
#define PLATFORM_CACHE43_TYPE                  0x2

#define PLATFORM_CACHE44_FLAGS                 0xFF
#define PLATFORM_CACHE44_OFFSET                0x7bc
#define PLATFORM_CACHE44_NEXT_LEVEL_INDEX      43
#define PLATFORM_CACHE44_SIZE                  0x10000
#define PLATFORM_CACHE44_CACHE_ID              0xe002
#define PLATFORM_CACHE44_IS_PRIVATE            0x1
#define PLATFORM_CACHE44_TYPE                  0x1

#define PLATFORM_CACHE45_FLAGS                 0xFF
#define PLATFORM_CACHE45_OFFSET                0x824
#define PLATFORM_CACHE45_NEXT_LEVEL_INDEX      46
#define PLATFORM_CACHE45_SIZE                  0x10000
#define PLATFORM_CACHE45_CACHE_ID              0xf001
#define PLATFORM_CACHE45_IS_PRIVATE            0x1
#define PLATFORM_CACHE45_TYPE                  0x0

#define PLATFORM_CACHE46_FLAGS                 0xFF
#define PLATFORM_CACHE46_OFFSET                0x85c
#define PLATFORM_CACHE46_NEXT_LEVEL_INDEX      -1
#define PLATFORM_CACHE46_SIZE                  0x100000
#define PLATFORM_CACHE46_CACHE_ID              0xf003
#define PLATFORM_CACHE46_IS_PRIVATE            0x1
#define PLATFORM_CACHE46_TYPE                  0x2

#define PLATFORM_CACHE47_FLAGS                 0xFF
#define PLATFORM_CACHE47_OFFSET                0x840
#define PLATFORM_CACHE47_NEXT_LEVEL_INDEX      46
#define PLATFORM_CACHE47_SIZE                  0x10000
#define PLATFORM_CACHE47_CACHE_ID              0xf002
#define PLATFORM_CACHE47_IS_PRIVATE            0x1
#define PLATFORM_CACHE47_TYPE                  0x1


#define PLATFORM_PPTT0_CACHEID0  0x1
#define PLATFORM_PPTT0_CACHEID1  0x2

#define PLATFORM_PPTT1_CACHEID0  0x1001
#define PLATFORM_PPTT1_CACHEID1  0x1002

#define PLATFORM_PPTT2_CACHEID0  0x2001
#define PLATFORM_PPTT2_CACHEID1  0x2002

#define PLATFORM_PPTT3_CACHEID0  0x3001
#define PLATFORM_PPTT3_CACHEID1  0x3002

#define PLATFORM_PPTT4_CACHEID0  0x4001
#define PLATFORM_PPTT4_CACHEID1  0x4002

#define PLATFORM_PPTT5_CACHEID0  0x5001
#define PLATFORM_PPTT5_CACHEID1  0x5002

#define PLATFORM_PPTT6_CACHEID0  0x6001
#define PLATFORM_PPTT6_CACHEID1  0x6002

#define PLATFORM_PPTT7_CACHEID0  0x7001
#define PLATFORM_PPTT7_CACHEID1  0x7002

#define PLATFORM_PPTT8_CACHEID0  0x8001
#define PLATFORM_PPTT8_CACHEID1  0x8002

#define PLATFORM_PPTT9_CACHEID0  0x9001
#define PLATFORM_PPTT9_CACHEID1  0x9002

#define PLATFORM_PPTT10_CACHEID0 0xa001
#define PLATFORM_PPTT10_CACHEID1 0xa002

#define PLATFORM_PPTT11_CACHEID0 0xb001
#define PLATFORM_PPTT11_CACHEID1 0xb002

#define PLATFORM_PPTT12_CACHEID0 0xc001
#define PLATFORM_PPTT12_CACHEID1 0xc002

#define PLATFORM_PPTT13_CACHEID0 0xd001
#define PLATFORM_PPTT13_CACHEID1 0xd002

#define PLATFORM_PPTT14_CACHEID0 0xe001
#define PLATFORM_PPTT14_CACHEID1 0xe002

#define PLATFORM_PPTT15_CACHEID0 0xf001
#define PLATFORM_PPTT15_CACHEID1 0xf002

/* SRAT config */

#define PLATFORM_OVERRIDE_NUM_SRAT_ENTRIES  17
#define PLATFORM_OVERRIDE_MEM_AFF_CNT       1
#define PLATFORM_OVERRIDE_GICC_AFF_CNT      16

#define PLATFORM_SRAT_MEM0_PROX_DOMAIN      0x0
#define PLATFORM_SRAT_MEM0_FLAGS            0x1
#define PLATFORM_SRAT_MEM0_ADDR_BASE        0x8080000000
#define PLATFORM_SRAT_MEM0_ADDR_LEN         0x3F7F7FFFFFF

#define PLATFORM_SRAT_GICC0_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC0_PROC_UID        0x0
#define PLATFORM_SRAT_GICC0_FLAGS           0x1
#define PLATFORM_SRAT_GICC0_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC1_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC1_PROC_UID        0x1
#define PLATFORM_SRAT_GICC1_FLAGS           0x1
#define PLATFORM_SRAT_GICC1_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC2_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC2_PROC_UID        0x2
#define PLATFORM_SRAT_GICC2_FLAGS           0x1
#define PLATFORM_SRAT_GICC2_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC3_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC3_PROC_UID        0x3
#define PLATFORM_SRAT_GICC3_FLAGS           0x1
#define PLATFORM_SRAT_GICC3_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC4_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC4_PROC_UID        0x4
#define PLATFORM_SRAT_GICC4_FLAGS           0x1
#define PLATFORM_SRAT_GICC4_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC5_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC5_PROC_UID        0x5
#define PLATFORM_SRAT_GICC5_FLAGS           0x1
#define PLATFORM_SRAT_GICC5_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC6_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC6_PROC_UID        0x6
#define PLATFORM_SRAT_GICC6_FLAGS           0x1
#define PLATFORM_SRAT_GICC6_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC7_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC7_PROC_UID        0x7
#define PLATFORM_SRAT_GICC7_FLAGS           0x1
#define PLATFORM_SRAT_GICC7_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC8_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC8_PROC_UID        0x8
#define PLATFORM_SRAT_GICC8_FLAGS           0x1
#define PLATFORM_SRAT_GICC8_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC9_PROX_DOMAIN     0x0
#define PLATFORM_SRAT_GICC9_PROC_UID        0x9
#define PLATFORM_SRAT_GICC9_FLAGS           0x1
#define PLATFORM_SRAT_GICC9_CLK_DOMAIN      0x0

#define PLATFORM_SRAT_GICC10_PROX_DOMAIN    0x0
#define PLATFORM_SRAT_GICC10_PROC_UID       0xA
#define PLATFORM_SRAT_GICC10_FLAGS          0x1
#define PLATFORM_SRAT_GICC10_CLK_DOMAIN     0x0

#define PLATFORM_SRAT_GICC11_PROX_DOMAIN    0x0
#define PLATFORM_SRAT_GICC11_PROC_UID       0xB
#define PLATFORM_SRAT_GICC11_FLAGS          0x1
#define PLATFORM_SRAT_GICC11_CLK_DOMAIN     0x0

#define PLATFORM_SRAT_GICC12_PROX_DOMAIN    0x0
#define PLATFORM_SRAT_GICC12_PROC_UID       0xC
#define PLATFORM_SRAT_GICC12_FLAGS          0x1
#define PLATFORM_SRAT_GICC12_CLK_DOMAIN     0x0

#define PLATFORM_SRAT_GICC13_PROX_DOMAIN    0x0
#define PLATFORM_SRAT_GICC13_PROC_UID       0xD
#define PLATFORM_SRAT_GICC13_FLAGS          0x1
#define PLATFORM_SRAT_GICC13_CLK_DOMAIN     0x0

#define PLATFORM_SRAT_GICC14_PROX_DOMAIN    0x0
#define PLATFORM_SRAT_GICC14_PROC_UID       0xE
#define PLATFORM_SRAT_GICC14_FLAGS          0x1
#define PLATFORM_SRAT_GICC14_CLK_DOMAIN     0x0

#define PLATFORM_SRAT_GICC15_PROX_DOMAIN    0x0
#define PLATFORM_SRAT_GICC15_PROC_UID       0xF
#define PLATFORM_SRAT_GICC15_FLAGS          0x1
#define PLATFORM_SRAT_GICC15_CLK_DOMAIN     0x0

#define PLATFORM_OVERRIDE_NUM_OF_HMAT_PROX_DOMAIN 1
#define PLATFORM_OVERRIDE_HMAT_MEM_ENTRIES    0x4

#define HMAT_NODE_MEM_SLLBIC                  0x1
#define HMAT_NODE_MEM_SLLBIC_DATA_TYPE        0x3
#define HMAT_NODE_MEM_SLLBIC_FLAGS            0x0
#define HMAT_NODE_MEM_SLLBIC_ENTRY_BASE_UNIT  0x64

#define PLATFORM_HMAT_MEM0_PROX_DOMAIN        0x0
#define PLATFORM_HMAT_MEM0_MAX_WRITE_BW       0x82
#define PLATFORM_HMAT_MEM0_MAX_READ_BW        0x82

#define PLATFORM_HMAT_MEM1_PROX_DOMAIN        0x1
#define PLATFORM_HMAT_MEM1_MAX_WRITE_BW       0x8c
#define PLATFORM_HMAT_MEM1_MAX_READ_BW        0x8c

#define PLATFORM_HMAT_MEM2_PROX_DOMAIN        0x2
#define PLATFORM_HMAT_MEM2_MAX_WRITE_BW       0x96
#define PLATFORM_HMAT_MEM2_MAX_READ_BW        0x96

#define PLATFORM_HMAT_MEM3_PROX_DOMAIN        0x3
#define PLATFORM_HMAT_MEM3_MAX_WRITE_BW       0xa0
#define PLATFORM_HMAT_MEM3_MAX_READ_BW        0xa0

/* APMT config */

#define MAX_NUM_OF_PMU_SUPPORTED              512
#define PLATFORM_OVERRIDE_PMU_NODE_CNT        0x1

#define PLATFORM_PMU_NODE0_BASE0              0x1010028000
#define PLATFORM_PMU_NODE0_BASE1              0x0
#define PLATFORM_PMU_NODE0_TYPE               0x2
#define PLATFORM_PMU_NODE0_PRI_INSTANCE       0x0
#define PLATFORM_PMU_NODE0_SEC_INSTANCE       0x0
#define PLATFORM_PMU_NODE0_DUAL_PAGE_EXT      0x0

/* RAS Config */
#define RAS_MAX_NUM_NODES                     140
#define RAS_MAX_INTR_TYPE                     0x2

#define PLATFORM_OVERRIDE_NUM_RAS_NODES       0x1

#define PLATFORM_OVERRIDE_NUM_PE_RAS_NODES    0x1
#define PLATFORM_OVERRIDE_NUM_MC_RAS_NODES    0x0

/* RAS Node Data */
#define PLATFORM_RAS_NODE0_LENGTH             0x0
#define PLATFORM_RAS_NODE0_NUM_INTR_ENTRY     0x1

#define PLATFORM_RAS_NODE0_PE_PROCESSOR_ID    0x0
#define PLATFORM_RAS_NODE0_PE_RES_TYPE        0x0
#define PLATFORM_RAS_NODE0_PE_FLAGS           0x0
#define PLATFORM_RAS_NODE0_PE_AFF             0x0
#define PLATFORM_RAS_NODE0_PE_RES_DATA        0x0

#define PLATFORM_RAS_NODE0_INTF_TYPE          0x0
#define PLATFORM_RAS_NODE0_INTF_FLAGS         0x0
#define PLATFORM_RAS_NODE0_INTF_BASE          0x0
#define PLATFORM_RAS_NODE0_INTF_START_REC     0x1
#define PLATFORM_RAS_NODE0_INTF_NUM_REC       0x1
#define PLATFORM_RAS_NODE0_INTF_ERR_REC_IMP   0x0
#define PLATFORM_RAS_NODE0_INTF_ERR_STATUS    0x0
#define PLATFORM_RAS_NODE0_INTF_ADDR_MODE     0x0

#define PLATFORM_RAS_NODE0_INTR0_TYPE         0x0
#define PLATFORM_RAS_NODE0_INTR0_FLAG         0x1
#define PLATFORM_RAS_NODE0_INTR0_GSIV         0x11
#define PLATFORM_RAS_NODE0_INTR0_ITS_ID       0x0

#define RAS2_MAX_NUM_BLOCKS                   0x4

#define PLATFORM_OVERRIDE_NUM_RAS2_BLOCK      0x3
#define PLATFORM_OVERRIDE_NUM_RAS2_MEM_BLOCK  0x3

#define PLATFORM_OVERRIDE_RAS2_BLOCK0_PROXIMITY             0x0
#define PLATFORM_OVERRIDE_RAS2_BLOCK0_PATROL_SCRUB_SUPPORT  0x1
#define PLATFORM_OVERRIDE_RAS2_BLOCK1_PROXIMITY             0x1
#define PLATFORM_OVERRIDE_RAS2_BLOCK1_PATROL_SCRUB_SUPPORT  0x1
#define PLATFORM_OVERRIDE_RAS2_BLOCK2_PROXIMITY             0x2
#define PLATFORM_OVERRIDE_RAS2_BLOCK2_PATROL_SCRUB_SUPPORT  0x1

/*MPAM Config*/
#define MPAM_MAX_MSC_NODE                     0x1
#define MPAM_MAX_RSRC_NODE                    0x1
#define PLATFORM_MPAM_MSC_COUNT               0x1

#define PLATFORM_MPAM_MSC0_BASE_ADDR          0x1010028000
#define PLATFORM_MPAM_MSC0_ADDR_LEN           0x2004
#define PLATFORM_MPAM_MSC0_MAX_NRDY           10000000
#define PLATFORM_MPAM_MSC0_RSRC_COUNT         0x1

#define PLATFORM_MPAM_MSC0_RSRC0_RIS_INDEX    0x0
#define PLATFORM_MPAM_MSC0_RSRC0_LOCATOR_TYPE 0x1
#define PLATFORM_MPAM_MSC0_RSRC0_DESCRIPTOR1  0x0
#define PLATFORM_MPAM_MSC0_RSRC0_DESCRIPTOR2  0x0

/** End config **/
